[package]
name = "bevy_debug_grid"
description = "A bevy plugin for creating grids, for debugging purposes"
version = "0.1.1"
repository = "https://github.com/romenjelly/bevy_debug_grid"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]
exclude = [
    "/examples/",
    "/assets/",
]

[dependencies]
bevy = { version = "0.11", default-features = false, features = [
    "bevy_render",
    "bevy_pbr",
    "bevy_asset",
] }

[dev-dependencies]
bevy = "0.11"
##todo change after spectator migrated main
bevy_spectator = {git="https://github.com/GodGotzi/bevy_spectator.git", rev = "0845106"}

[[example]]
name = "default_cube"
path = "examples/default_cube.rs"

[[example]]
name = "moving_grid"
path = "examples/moving_grid.rs"

[[example]]
name = "changing_grid"
path = "examples/changing_grid.rs"

[[example]]
name = "changing_grid_axis"
path = "examples/changing_grid_axis.rs"

[[example]]
name = "dynamic_floor_grid"
path = "examples/dynamic_floor_grid.rs"
